### PR TITLE
add flag for compilation with ghc-8

### PR DESCRIPTION
**Pull request by jwaldmann**
Hi. I wanted to use your library, but could not compile with ghc-8. I made the necessary (trivial) change, also in monad-mersenne-random. I can compile, but when I do `stack test`, I am getting output like this (it's different each time):
```
### Failure in: 3:0:do N crossovers         
    ./Tests/Internals/TestCrossover.hs:22
    4 crossovers
    expected: [[0,0,1,1],[1,1,0,0],[0,0,0,1],[1,1,1,0]]
     but got: [[1,0,0,0],[0,1,1,1],[1,1,0,0],[0,0,1,1]]
### Failure in: 3:1:do all crossovers       
    ./Tests/Internals/TestCrossover.hs:32
    all crossovers (2 genomes)
    expected: [[1,1,1,0],[0,0,0,1]]
     but got: [[1,1,0,0],[0,0,1,1]]
Cases: 35  Tried: 35  Errors: 0  Failures: 2
```

### CODE REVIEW

**Comment by astanin** [comment]
Hi @jwaldmann 

Thank you for the submission. Some questions regarding this PR.

1. Was there a reason to change source layout (move everything to src/)?

2. You moved NSGA2 implementation files from other-modules to exposed-modules, why? I considered this module to be full of implementation details which may have to be changed if someone wants to optimize the method.

3. You changed stack.yaml, but does the project still work with the older stack? I'd like to make sure that the project is usable with LTS Haskell 6.24. I'd rather to keep it as a default.

As for the tests failing, there are some tests that rely on a particular seeded sequence of random numbers. It appears that different versions of mersenne-random-pure64 are seeded differently. It happened before. I wouldn't care much about such tests. Probably it's time to switch to mwc-random anyway, and reimplement/bundle the analog of monad-mersenne-random within the project source tree.

If possible, I'd like to see this PR change this way:

 - fix only GHC8 compatibility issues (don't touch stack.yaml)
 - don't move code around unless necessary (I may accept rearrangement of the source code layout it as a separate PR)
 - drop dependency on monad-mersenne-random and bundle the implementation (copy `Rand` type and related stuff to Moo.Utils.MonadMersenneRandom module); @dons doesn't seem to be maintaining the package anyway
 - test on older stack

**Comment by astanin** [comment]
Oh, I see why you changed the layout. It's ok. Never mind.

**Comment by jwaldmann** [comment]
moved NSGA2 ... this is a side-effect of a cabal design issue: when you have test (and executable) sections in the cabal file, they can be made to build-depend on the library (I think they should), but then the modules to be tested must be exposed (I understand that this is not always nice).

**Comment by jwaldmann** [comment]
monad-mersenne-random .. dons said to me that I could "take over this library if necessary" (and push an updated version to hackage - apparently he cannot, at least not at the moment). I can do this. But I don't really know what this library does and how, so I don't really want to claim maintainership here. I just mechanically repaired the AMP breakage. Perhaps you want to take over? The thing has 3 reverse dependencies http://packdeps.haskellers.com/reverse/monad-mersenne-random

**Comment by GrandmasterShadowMorgue** [comment]
Hi, has there been any progress with this? I'd like to use this library with ghc 8.

**Comment by astanin** [comment]
These PR has been superseded by #9

**Pull request closed without merging**
